# Generated by Django 3.1.7 on 2021-05-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=40)),
                ('purchase', models.BooleanField()),
                ('favourite_food', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=30)),
                ('rating', models.IntegerField(max_length=1)),
                ('feed', models.CharField(max_length=300)),
            ],
        ),
    ]
