# Generated by Django 3.1.7 on 2021-05-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
