# Generated by Django 3.1.7 on 2021-05-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('menuimg', models.ImageField(upload_to='menu-items-images')),
                ('description', models.CharField(max_length=80)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
